- package.json
- pnpm-lock.yaml
This PR updates the `lint-staged` dependency from version `16.1.0` to version `16.1.2` across the project.
- **Dependency Update:** Upgraded `lint-staged` from `16.1.0` to `16.1.2`
> chore(deps): bump `lint-staged` from `16.1.0` to `16.1.2`

- apps/creator/package.json
- apps/learner/package.json
- packages/auth/package.json
- pnpm-lock.yaml
This PR updates the `svelte` dependency from version `5.33.4` to version `5.34.9` across the project.
- **Dependency Update:** Upgraded `svelte` from `5.33.4` to `5.34.9`
> chore(deps): bump `svelte` from `5.33.4` to `5.34.9`

- apps/creator/package.json
- apps/creator/src/app.html
- apps/learner/package.json
- apps/learner/src/app.html
- pnpm-lock.yaml
This PR updates the `tailwindcss` and `@tailwindcss/vite` dependency from version `4.1.7` to version `4.1.11` across the project.
- **Dependency Update:** Upgraded `tailwindcss` and `@tailwindcss/vite` from `4.1.7` to `4.1.11`
> chore(deps): bump `tailwindcss` and `@tailwindcss/vite` from `4.1.7` to `4.1.11`

- apps/creator/package.json
- apps/learner/package.json
- packages/auth/package.json
- pnpm-lock.yaml
This PR updates the `@sveltejs/kit` dependency from version `2.21.1` to version `2.22.2` across the project.
- **Dependency Update:** Upgraded `@sveltejs/kit` from `2.21.1` to `2.22.2`
> chore(deps): bump `@sveltejs/kit` from `2.21.1` to `2.22.2`

- package.json
- pnpm-lock.yaml
This PR updates the `prettier-plugin-tailwindcss` dependency from version `0.6.11` to version `0.6.13` across the project.
- **Dependency Update:** Upgraded `prettier-plugin-tailwindcss` from `0.6.11` to `0.6.13`
> chore(deps): bump `prettier-plugin-tailwindcss` from `0.6.11` to `0.6.13`

- apps/creator/package.json
- apps/learner/package.json
- packages/auth/package.json
- pnpm-lock.yaml
This PR updates the `@sveltejs/vite-plugin-svelte` dependency from version `5.0.3` to version `5.1.0` across the project.
- **Dependency Update:** Upgraded `@sveltejs/vite-plugin-svelte` from `5.0.3` to `5.1.0`
> chore(deps): bump `@sveltejs/vite-plugin-svelte` from `5.0.3` to `5.1.0`

- apps/creator/package.json
- apps/learner/package.json
- patches/svelte-check.patch
- pnpm-lock.yaml
This PR updates the `svelte-check` dependency from version `4.2.1` to version `4.2.2` across the project.
- **Dependency Update:** Upgraded `svelte-check` from `4.2.1` to `4.2.2`
> chore(deps): bump `svelte-check` from `4.2.1` to `4.2.2`

- apps/learner/src/routes/content/[id]/quiz/+page.server.ts
- apps/learner/src/routes/content/[id]/quiz/+page.svelte
Closes #49 
This PR adds the quiz component for learner which is rendered sequentially.
- added `+page.server.svelte` in `quiz` (currently values are hardcoded, will be dynamic based on content once DB integration is complete)
- updated UI design for quiz page in `+page.svelte` in `quiz`
Note: the album cover (as shown in figma) is currently not implemented as design is yet to be firmed up.
> feat(learner): add quiz page with hardcoded data

- apps/learner/package.json
- apps/learner/src/routes/content/[id]/+page.server.ts
- apps/learner/src/routes/content/[id]/+page.svelte
- pnpm-lock.yaml
Closes #59 
This PR introduces a new Learning Unit page. It sets up the structure for retrieving and displaying learning unit data, currently using hardcoded data as a placeholder. Future work will connect this page to the database. For now, the tags of a learning unit are always displayed in purple. Future work will map each tag to a specific color, either on the client or server side.
- Added a new Learning Unit page to the learner app
- Implemented server-side retrieval of learning unit data using hardcoded data
> feat(learner): add learning unit page with hardcoded data

- apps/learner/src/app.html
- apps/learner/src/lib/components/Collection.svelte
- apps/learner/src/lib/components/LearningUnit.svelte
- apps/learner/src/routes/(app)/+layout.svelte
- apps/learner/src/routes/(app)/+page.svelte
- apps/learner/src/routes/(app)/explore/+page.svelte
- apps/learner/src/routes/(app)/learning/+page.svelte
- apps/learner/src/routes/+error.svelte
- apps/learner/src/routes/+layout.svelte
- apps/learner/src/routes/collection/[id]/+page.svelte
- apps/learner/src/routes/content/[id]/+page.svelte
- apps/learner/src/routes/content/[id]/quiz/+layout.svelte
- apps/learner/src/routes/profile/+page.svelte
This PR standardises the layout across all learner pages by implementing a consistent `header` and `main` element structure. The `header` element contains navigation functionality and CTAs that remain visible throughout scrolling, while the `main` element contains the primary content. Page padding has been optimised for mobile screens (`16px` horizontal, `12px` vertical) to provide more content space. This improves the overall user experience and visual consistency throughout the application.
- Standardised layout structure with `header` and `main` elements across all learner pages
- Adjusted page padding from 24px all sides to 16px horizontal and 12px vertical for better mobile content space
- Added dynamic bottom border/separator that appears when scrolling downwards
- Enhanced visual …
> feat(learner): update layout across all pages except the quiz page

- apps/learner/src/lib/components/FloatingPlayer.svelte
- apps/learner/src/routes/(app)/+page.svelte
Closes https://github.com/String-sg/onward/issues/62
This update introduces the `FloatingPlayer` component, which allows users to toggle between play and pause states for podcasts. It provides a simple and reusable design for managing playback functionality within the learner app.
- Implemented isplaying state to dynamically control playback.
- Added onplay callback to handle play/pause events.
- Created a reusable FloatingPlayer component with a modern UI.
The functionality to ensure the floating player persists across page navigations will be addressed in a _future pull request._
> feat(learner): add floating podcast player

- package.json
- pnpm-lock.yaml
This PR updates the `eslint` and `@eslint/js` dependency from version `9.30.0` to version `9.31.0` across the project.
- **Dependency Update:** Upgraded `eslint` and `@eslint/js` from `9.30.0` to `9.31.0`
> chore(deps): bump `eslint` and `@eslint/js` from `9.30.0` to `9.31.0`

- package.json
- pnpm-lock.yaml
This PR updates the `typescript-eslint` dependency from version `8.35.0` to version `8.37.0`.
- **Dependency Update:** Upgraded `typescript-eslint` from `8.35.0` to `8.37.0`
> chore(deps): bump `typescript-eslint` from `8.35.0` to `8.37.0`

- package.json
- pnpm-lock.yaml
This PR updates the `eslint-plugin-svelte` dependency from version `3.10.1` to version `3.11.0`.
- **Dependency Update:** Upgraded `eslint-plugin-svelte` from `3.10.1` to `3.11.0`
> chore(deps): bump `eslint-plugin-svelte` from `3.10.1` to `3.11.0`

- apps/creator/package.json
- apps/learner/package.json
- packages/auth/package.json
- pnpm-lock.yaml
This PR updates the `@sveltejs/kit` dependency from version `2.22.2` to version `2.25.1`.
- **Dependency Update:** Upgraded `@sveltejs/kit` from `2.22.2` to `2.25.1`
> chore(deps): bump `@sveltejs/kit` from `2.22.2` to `2.25.1`

- apps/creator/package.json
- apps/learner/package.json
- packages/auth/package.json
- pnpm-lock.yaml
This PR updates the `vite` dependency from version `6.3.5` to version `7.0.5`.
- **Dependency Update:** Upgraded `vite` from `6.3.5` to `7.0.5`
> chore(deps): bump `vite` from `6.3.5` to `7.0.5`

- apps/learner/src/routes/(app)/+layout.svelte
- apps/learner/src/routes/collection/[id]/+page.svelte
- apps/learner/src/routes/content/[id]/+page.svelte
This PR fixes a bug causing the header’s bottom line to flash on page load.
- Changed the default state of `isWithinViewport` from `false` to `true`
> fix(learner): stop header bottom line from flashing on page load

- apps/learner/src/lib/components/FloatingChat.svelte
- apps/learner/src/lib/components/FloatingPlayer.svelte
This PR aims to remove the white background that's causing the glass effect to disappear. This was an aftereffect from #123 where during refactor of the floating container, the styling of the buttons got changed unintentionally
- remove white background
- added `inset-shadow-slate-200` and `border border-zinc-200` to make the floating components more distinct
> fix(learner): remove white bg that's causing the removal of glass effect

- apps/learner/src/routes/content/[id]/quiz/+layout.svelte
- apps/learner/src/routes/content/[id]/quiz/+page.svelte
This PR aims to standardise the layout of quiz with the rest of the learner app (reference with #111)
- removed layout file since there's no reusability with other non-quiz related pages
- applied styling on feedback modal to also follow the same layout styling
- updated the Back button styling to use a circular shape instead of the existing oval-ish shape (note this is only applied on quiz and not on the rest of the app, which will be handled in a separate change)
- made the Check Answer sticky at the bottom as per discussion with Wondo
- added z-index for feedback modal
- updated design based on latest figma updates
> feat(learner): Standardise quiz page layout

- apps/learner/src/lib/components/Button/Button.svelte
- apps/learner/src/lib/components/LearningUnit.svelte
- apps/learner/src/routes/content/[id]/+page.svelte
- apps/learner/src/routes/content/[id]/quiz/+page.svelte
Closes #133
This update reverts a previous layout change to the `LearningUnit` progress indicator (https://github.com/String-sg/onward/pull/116) and applies visual improvements to the play button. The goal is to maintain a consistent UI while refining the visual experience for learners.
- **Reverted**: feat(learner): reposition the LearningUnit progress indicator (#116)
- Updated the play button with new background color and border styling for improved contrast and clarity
- Reduce `Play` icon size from `24x24` to `16x16` in `LearningUnit` component
> feat(learner): update play button and revert previous layout change in `LearningUnit` component

- apps/learner/src/routes/collection/[id]/+page.svelte
- apps/learner/src/routes/content/[id]/+page.svelte
This PR adds focus effect to the navigation buttons and adjusted their padding from `px-3 py-4` to `p-4`.
- Added focus effect to the navigation buttons on `Collection` and `LearningUnit` pages
- Update the padding of the navigation buttons from `px-3 py-4` to `p-4` on `Collection` and `LearningUnit` pages
> feat(learner): add focus effect to navigation buttons and adjust their padding from `px-3 py-4` to `p-4` on `Collection` and `LearningUnit` pages

- apps/learner/src/lib/components/FloatingChat.svelte
This PR updates the icon for the `FloatingChat` component.
- Updated the icon for the `FloatingChat` component
> feat(learner): update icon for `FloatingChat` component

- apps/learner/src/lib/helpers/audio-state.svelte.ts
- apps/learner/src/routes/(app)/+page.svelte
Closes https://github.com/String-sg/onward/issues/142
Moving the floating player toggle to the audio state to centralize the logic related to the player
- Moved the toggle flag to show the floating player
> feat(learner): move floating player toggle to audio state

- apps/creator/package.json
- apps/learner/package.json
- apps/learner/src/lib/components/FloatingChat.svelte
By default `svelte-check` does not return a non-zero exit code on warnings. This PR adds the `--fail-on-warnings` flag to all `svelte-check` commands so that warnings will cause a non-zero exit code, allowing the CI to fail.
- Added `--fail-on-warnings` flag to `svelte-check` in learner and creator apps
- Added `aria-label` to `FloatingChat` component
> fix: enable `svelte-check` to fail on warnings in CI

- apps/learner/src/lib/components/FloatingChat.svelte
- apps/learner/src/lib/components/FloatingPlayer.svelte
- apps/learner/src/routes/(app)/+layout.svelte
- apps/learner/src/routes/(app)/+page.svelte
This PR enhances the `FloatingPlayer` and `FloatingChat` components by adding a slightly transparent white background and a hover effect. It also introduces additional bottom padding to the app layout to accommodate the floating components when scrolled to the bottom.
- Added `bg-white/30` to `FloatingPlayer` and `FloatingChat` components
- Updated the shadow of `FloatingPlayer` and `FloatingChat` components from `shadow-lg` to `shadow-sm`
- Updated the padding on `FloatingChat` component from `p-5` to `p-5.5`
- Updated the padding on `FloatingPlayer` component from `p-3` to `px-3 py-3.5`
- Added hover effect for `FloatingPlayer` and `FloatingChat` components
- Added additional bottom padding to the app layout to accommodate the floating components
> feat(learner): update `FloatingPlayer` and `FloatingChat` components with slightly transparent white background and hover effect

- package.json
- pnpm-lock.yaml
This PR bumps `eslint` and `@eslint/js` from `9.31.0` to `9.33.0`.
- Bumped `eslint` and `@eslint/js` from `9.31.0` to `9.33.0`
> chore(deps): bump `eslint` and `@eslint/js` from `9.31.0` to `9.33.0`

- package.json
- pnpm-lock.yaml
This PR bumps `typescript-eslint` from `8.37.0` to `8.39.0`.
- Bumped `typescript-eslint` from `8.37.0` to `8.39.0`
> chore(deps): bump `typescript-eslint` from `8.37.0` to `8.39.0`

- apps/creator/package.json
- apps/learner/package.json
- packages/auth/package.json
- pnpm-lock.yaml
This PR bumps `typescript` from `5.8.3` to `5.9.2`.
- Bumped `typescript` from `5.8.3` to `5.9.2`
> chore(deps): bump `typescript` from `5.8.3` to `5.9.2`

- apps/creator/package.json
- apps/learner/package.json
- packages/auth/package.json
- pnpm-lock.yaml
This PR bumps `svelte` from `5.34.9` to `5.38.0`.
- Bumped `svelte` from `5.34.9` to `5.38.0`
> chore(deps): bump `svelte` from `5.34.9` to `5.38.0`

- apps/creator/package.json
- apps/learner/package.json
- packages/auth/package.json
- pnpm-lock.yaml
This PR bumps `vite` from `7.0.5` to `7.1.1`.
- Bumped `vite` from `7.0.5` to `7.1.1`
> chore(deps): bump `vite` from `7.0.5` to `7.1.1`

- apps/learner/src/lib/states/player.svelte.ts
- apps/learner/src/routes/(app)/+page.server.ts
- apps/learner/src/routes/content/[id]/+page.server.ts
- apps/learner/src/routes/content/[id]/+page.svelte
This PR applies the **Player State** on Learning Content to synchronize the player button UI.
- Added Player event handlers for the Learning Content button UI
- Added Play, Pause, and Resume button UI.
- Change `Track` interface `id` to a number to align with LearningUnit data type
> feat(learner): sync player state on learning content

- apps/learner/src/app.css
This PR adds custom scrollbar styling to ensure it integrates seamlessly with the existing colour palette.
- Added custom scrollbar styling using `slate-950` at 20% opacity with a transparent background
> feat(learner): add custom scrollbar styling

- apps/learner/src/app.html
- apps/learner/src/lib/components/Starfield/Starfield.svelte
- apps/learner/src/routes/(protected)/(core)/+layout.svelte
- apps/learner/src/routes/(protected)/(core)/+page.svelte
- apps/learner/src/routes/(protected)/(core)/explore/+page.svelte
- apps/learner/src/routes/(protected)/(core)/learning/+page.server.ts
- apps/learner/src/routes/(protected)/(core)/learning/+page.svelte
- apps/learner/src/routes/(protected)/collection/[id]/+page.svelte
- apps/learner/src/routes/(protected)/content/[id]/+page.svelte
- apps/learner/src/routes/(protected)/profile/+page.svelte
- apps/learner/src/routes/+error.svelte
- apps/learner/src/routes/login/+page.svelte
This PR replaces `min-h-full` with `min-h-svh` on all `main` containers to ensure the correct viewport height, rather than relying on parent elements to provide it. The quiz page and chat view modal will be updated in separate PRs.
- Applied `min-h-svh` to all `main` containers to set the correct viewport height
- Moved the `main` container from the core layout into individual pages for consistency
- Added bottom padding on certain pages to make space for the `NowPlayingBar` and `ChatWidget` components
> feat(learner): standarise page layout

- apps/learner/src/lib/states/player.svelte.ts
- apps/learner/src/routes/(protected)/content/[id]/+page.server.ts
- prisma/migrations/20250908080148_add_summary_to_learning_unit_table/migration.sql
- prisma/schema.prisma
Implement server-side data fetching for the learner content page using Prisma, and extend the `LearningUnit` model with a `summary` field. This enables the page to load a learning unit by ID from PostgreSQL and display its metadata (`title`, `tags`, `summary`, `URL`, `timestamps`). 
* Added server-side load function (+page.server.ts) to fetch a LearningUnit by ID via Prisma
* Parses params.id as BigInt
* Selects id, tags, title, summary, contentURL, createdAt
* Returns 404 when the learning unit is not found
* Serializes BigInt and Date fields for the client
* Introduced summary field to the LearningUnit table/model
* Updated Prisma schema
* Ran migration to add summary column
* Ensured proper `Prisma` client lifecycle
* Instantiated `PrismaClient` in the server load and `disconnected` in …
> feat(learner): add content page data

- apps/learner/src/routes/(protected)/profile/+page.server.ts
Added functionality to track learning unit activity and completion based on dynamic date ranges. This includes calculating the start of the current month and week (with Monday as the start of the week) and querying data accordingly.
- Integrated `date-fns` for date calculations:
- Used `startOfMonth` to calculate the first day of the current month.
- Used `startOfWeek` with `{ weekStartsOn: 1 }` to ensure Monday is treated as the start of the week.
- Updated learning unit queries:
- Used `updatedAt` to track recent activity.
- Added filtering logic for weekly and monthly activity based on calculated date ranges.
- Improved session validation:
- Added `validateSession` function to ensure user authentication and handle invalid user IDs gracefully.
- Enhanced the `load` function:
- Fetched …
> feat(learner): update profile content data with dynamic data

- apps/learner/prisma/migrations/20250918035634_replace_name_with_code_and_label_in_tags_table/migration.sql
- apps/learner/prisma/migrations/20250918182401_update_code_length_in_tag_table/migration.sql
- apps/learner/prisma/schema.prisma
- apps/learner/prisma/seed.ts
- apps/learner/src/lib/helpers/index.ts
- apps/learner/src/lib/helpers/mapping.ts
- apps/learner/src/lib/states/player.svelte.ts
- apps/learner/src/routes/(protected)/(core)/+page.server.ts
- apps/learner/src/routes/(protected)/(core)/+page.svelte
- apps/learner/src/routes/(protected)/content/[id]/+page.server.ts
- apps/learner/src/routes/(protected)/content/[id]/+page.svelte
This PR replaces `name` column with `code` and `label` in tags table. This is to guard against possible frequent name changes which will affect mapping to a color in the frontend which would lead to data migration and code changes.
- Replaced `name` column with `code` and `label` columns in tags table
- Added a mapping helper `tagCodeToBadgeVariant` for badge variants
> feat(learner): replace `name` column with `code` and `label` columns in tags table

- apps/learner/prisma/migrations/20250918030826_add_created_by_to_learning_units_table/migration.sql
- apps/learner/prisma/migrations/20250918120241_add_type_to_collections_table/migration.sql
- apps/learner/prisma/schema.prisma
- apps/learner/prisma/seed.ts
- apps/learner/src/lib/components/Collection/Collection.svelte
- apps/learner/src/lib/components/LearningUnit/LearningUnit.svelte
- apps/learner/src/routes/(protected)/(core)/+page.server.ts
- apps/learner/src/routes/(protected)/(core)/+page.svelte
- apps/learner/src/routes/(protected)/(core)/explore/+page.server.ts
- apps/learner/src/routes/(protected)/(core)/explore/+page.svelte
- apps/learner/src/routes/(protected)/(core)/learning/+page.server.ts
- apps/learner/src/routes/(protected)/(core)/learning/+page.svelte
- apps/learner/src/routes/(protected)/collection/[id]/+page.server.ts
- apps/learner/src/routes/(protected)/collection/[id]/+page.svelte
- apps/learner/src/routes/(protected)/content/[id]/+page.server.ts
- apps/learner/src/routes/(protected)/content/[id]/+page.svelte
- apps/learner/src/routes/(protected)/usercollection/[id]/+page.server.ts
- apps/learner/src/routes/(protected)/usercollection/[id]/+page.svelte
Closes #195
This PR aims to replace hardcoded data with actual data from database. This is done through implementing server-side data fetching for the learner explore page using Prisma, and extend the `LearningUnit` model with a `createdBy` field. This enables the page to load top 4 learning units and collections from the database.
- Added server-side load function (`+page.server.ts`) to fetch first 4 `LearningUnits` and `Collections`
- Added `created_by` to `LearningUnit` model
- Updated `LearningUnit` component with `createdAt` and `createdBy` props to get actual data instead of hardcoded data
- Updated all pages with latest props
> feat(learner): enhance explore page to get data from database

- .github/workflows/release.yaml
This PR add missing permission to the release workflow.
- Added `id_token: write` to release workflow permission
> ci: add missing permission to release workflow

- CHANGELOG.md
- apps/learner/package.json
- ci: add missing permission to release workflow ([#245](https://github.com/String-sg/onward/pull/245)) ([b774ef7](https://github.com/String-sg/onward/commit/b774ef7b336ad5c13e13c8a767749aac9b8f57d3))
> release: v0.0.2

- apps/learner/src/routes/(protected)/(core)/learning/+page.svelte
- apps/learner/src/routes/(protected)/(core)/learning/collection/[id]/+page.server.ts
- apps/learner/src/routes/(protected)/(core)/learning/collection/[id]/+page@(protected).svelte
This update enhances the `learning` collection feature by adding a server-side `load` function to fetch collection data and learning units dynamically, with error handling for missing collections. The route has been updated from `/usercollection/:id `to `/learning/collection/:id`, and the collection title is now rendered dynamically on the frontend. 
- Added a new server-side loader to fetch collection and learning unit data dynamically.
- Changed the route structure from `/usercollection/:id` to `/learning/collection/:id` for a more intuitive hierarchy.
- Made the collection title dynamic, pulling data directly from the database.
- Implemented a (protected) layout for the page to break out of all the layouts and only inherit from (protected) layout.
Ref: …
> feat(learner): add dynamic `learning collection page` with content data

- apps/learner/src/app.css
Closes #235 
This pull request aligns the Tailwind prose color scheme. The Tailwind prose-slate color configuration aligns the element colors to our existing UI.
- Override the tailwind `prose-slate` color configuration.
> feat: customize the Tailwind typography prose-slate for chat markdown UI

- CHANGELOG.md
- apps/learner/package.json
- feat: add S3 proxy endpoint for podcasts ([#255](https://github.com/String-sg/onward/pull/255)) ([3450f78](https://github.com/String-sg/onward/commit/3450f7895f31cc36a87b5d16048fd26705d93fa4))
- feat: create favicon for glow ([#256](https://github.com/String-sg/onward/pull/256)) ([d122686](https://github.com/String-sg/onward/commit/d122686d712c6f0d8def21988079563d092719fd))
- feat: customize the Tailwind typography prose-slate for chat markdown UI ([#243](https://github.com/String-sg/onward/pull/243)) ([d2e8c73](https://github.com/String-sg/onward/commit/d2e8c73597cf7d9c07860c4e86ede1eeb70a77f1))
- feat: add `CLUSTER_HOSTNAME` env to weaviate container ([#252](https://github.com/String-sg/onward/pull/252)) ([7af4cec](https://github.com/String-sg/onward/commit/7af4cec764925021c306361fb2ea …
> release: v0.1.0
